name: React test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - run: npm test -- --watchAll --coverage
      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: coverage-report
          path: coverage
